application: chatbyip
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "999d"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  secure: always

- url: /.*
  script: chat_by_ip.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest # http://code.google.com/p/webapp-improved/downloads/list

builtins:
- deferred: on
- remote_api: on
- appstats: off

inbound_services:
- channel_presence