// Generated by CoffeeScript 1.3.3
(function() {
  var http, qs;

  http = require("http");

  qs = require("querystring");

  http.createServer(function(req, res) {
    console.log('asdf');
    res.writeHead(200, {
      "Content-Type": "text/plain"
    });
    console.log('asdf');
    fs.readFile(__dirname + "/views/chat.html", "utf8", function(err, text) {
      return res.send(text);
    });
    console.log(message);
    return res.end(message);
  }).listen(80, "0.0.0.0");

  console.log("Server running at http://0.0.0.0/");

}).call(this);
